var searchData=
[
  ['pain_20to_20specify_20the_20actions_20gmock_20sucks_0',['My mock object needs to do complex stuff. It&apos;s a lot of pain to specify the actions. gMock sucks!',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md194',1,'']]],
  ['panic_1',['I got a warning &quot;Uninteresting function call encountered - default action taken..&quot; Should I panic?',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md195',1,'']]],
  ['parameter_2',['Parameter',['../classcpp_1_1ast_1_1_parameter.html',1,'cpp::ast']]],
  ['parameter_20in_20an_20action_3',['Restricting the Type of an Argument or Parameter in an ACTION',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md175',1,'']]],
  ['parameter_20why_4',['MSVC gives me warning C4301 or C4373 when I define a mock method with a const parameter. Why?',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md183',1,'']]],
  ['parameterized_20abstract_20tests_5',['Creating Value-Parameterized Abstract Tests',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md47',1,'']]],
  ['parameterized_20actions_6',['Legacy macro-based parameterized Actions',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md174',1,'']]],
  ['parameterized_20matchers_20quickly_7',['Writing New Parameterized Matchers Quickly',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md168',1,'']]],
  ['parameterized_20test_20parameters_8',['Specifying Names for Value-Parameterized Test Parameters',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md48',1,'']]],
  ['parameterized_20tests_9',['parameterized tests',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md46',1,'How to Write Value-Parameterized Tests'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md84',1,'I need to test that different implementations of an interface satisfy some common requirements. Should I use typed tests or value-parameterized tests?'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md50',1,'Type-Parameterized Tests'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md45',1,'Value-Parameterized Tests']]],
  ['parameterizeddeathtest_10',['ParameterizedDeathTest',['../class_parameterized_death_test.html',1,'']]],
  ['parameterizedderivedtest_11',['ParameterizedDerivedTest',['../class_parameterized_derived_test.html',1,'']]],
  ['parameterizedtestfactory_12',['ParameterizedTestFactory',['../classtesting_1_1internal_1_1_parameterized_test_factory.html',1,'testing::internal']]],
  ['parameterizedtestsuiteinfo_13',['ParameterizedTestSuiteInfo',['../classtesting_1_1internal_1_1_parameterized_test_suite_info.html',1,'testing::internal']]],
  ['parameterizedtestsuiteinfobase_14',['ParameterizedTestSuiteInfoBase',['../classtesting_1_1internal_1_1_parameterized_test_suite_info_base.html',1,'testing::internal']]],
  ['parameterizedtestsuiteregistry_15',['ParameterizedTestSuiteRegistry',['../classtesting_1_1internal_1_1_parameterized_test_suite_registry.html',1,'testing::internal']]],
  ['parameters_16',['Specifying Names for Value-Parameterized Test Parameters',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md48',1,'']]],
  ['paramgenerator_17',['ParamGenerator',['../classtesting_1_1internal_1_1_param_generator.html',1,'testing::internal']]],
  ['paramgeneratorinterface_18',['ParamGeneratorInterface',['../classtesting_1_1internal_1_1_param_generator_interface.html',1,'testing::internal']]],
  ['paramgeneratorinterface_3c_20paramtype_20_3e_19',['ParamGeneratorInterface&lt; ParamType &gt;',['../classtesting_1_1internal_1_1_param_generator_interface.html',1,'testing::internal']]],
  ['paramgeneratorinterface_3c_3a_3astd_3a_3atuple_3c_20t_2e_2e_2e_20_3e_20_3e_20',['ParamGeneratorInterface&lt;::std::tuple&lt; T... &gt; &gt;',['../classtesting_1_1internal_1_1_param_generator_interface.html',1,'testing::internal']]],
  ['paramiterator_21',['ParamIterator',['../classtesting_1_1internal_1_1_param_iterator.html',1,'testing::internal']]],
  ['paramiteratorinterface_22',['ParamIteratorInterface',['../classtesting_1_1internal_1_1_param_iterator_interface.html',1,'testing::internal']]],
  ['paramiteratorinterface_3c_20paramtype_20_3e_23',['ParamIteratorInterface&lt; ParamType &gt;',['../classtesting_1_1internal_1_1_param_iterator_interface.html',1,'testing::internal']]],
  ['paramtest_24',['ParamTest',['../class_param_test.html',1,'']]],
  ['parent_20class_25',['Delegating Calls to a Parent Class',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md127',1,'']]],
  ['parentclass_26',['ParentClass',['../class_parent_class.html',1,'']]],
  ['parseflagstest_27',['ParseFlagsTest',['../classtesting_1_1_parse_flags_test.html',1,'testing']]],
  ['partially_20ordered_20calls_28',['Expecting Partially Ordered Calls',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#PartialOrder',1,'']]],
  ['particular_20expectation_20is_20not_20satisfied_20isn_20t_20this_20redundant_29',['I have a failed test where gMock tells me TWICE that a particular expectation is not satisfied. Isn&apos;t this redundant?',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md187',1,'']]],
  ['passed_20testpartresult_3a_3apassed_30',['passed {#TestPartResult::passed}',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md360',1,'']]],
  ['passed_20testresult_3a_3apassed_31',['Passed {#TestResult::Passed}',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md366',1,'']]],
  ['passed_20testsuite_3a_3apassed_32',['Passed {#TestSuite::Passed}',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md297',1,'']]],
  ['passed_20unittest_3a_3apassed_33',['Passed {#UnitTest::Passed}',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md332',1,'']]],
  ['passes_34',['Suppressing test passes',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md70',1,'']]],
  ['patch_35',['Contributing A Patch',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md3',1,'']]],
  ['pathlike_36',['PathLike',['../classfoo_1_1_path_like.html',1,'foo']]],
  ['perform_20an_20arbitrary_20action_20on_20a_20mock_20function_20s_20argument_37',['How can I perform an arbitrary action on a mock function&apos;s argument?',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md192',1,'']]],
  ['performing_20different_20actions_20based_20on_20the_20arguments_38',['Performing Different Actions Based on the Arguments',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md131',1,'']]],
  ['pkg_20config_20can_20t_20find_20googletest_39',['Help! pkg-config can&apos;t find GoogleTest!',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2pkgconfig.html#autotoc_md218',1,'']]],
  ['pkg_20config_20in_20a_20cross_20compilation_20setting_40',['Using pkg-config in a cross-compilation setting',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2pkgconfig.html#autotoc_md219',1,'']]],
  ['placement_41',['Assertion Placement',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md25',1,'']]],
  ['platforms_42',['platforms',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2platforms.html',1,'Supported Platforms'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2_r_e_a_d_m_e.html#autotoc_md417',1,'Supported Platforms']]],
  ['please_20be_20friendly_43',['Please Be Friendly',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md5',1,'']]],
  ['please_20note_3a_44',['please note:',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2googletest_2scripts_2_r_e_a_d_m_e.html',1,'Please Note:'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2googlemock_2scripts_2_r_e_a_d_m_e.html',1,'Please Note:']]],
  ['point_20comparison_45',['point comparison',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md19',1,'Floating-Point Comparison'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2reference_2assertions.html#floating-point',1,'Floating-Point Comparison']]],
  ['point_20matchers_46',['Floating-Point Matchers',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2reference_2matchers.html#FpMatchers',1,'']]],
  ['point_20predicate_20format_20functions_47',['Floating-Point Predicate-Format Functions',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md20',1,'']]],
  ['pointed_20to_20by_20a_20pointer_20argument_48',['Validating the Value Pointed to by a Pointer Argument',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md138',1,'']]],
  ['pointer_20argument_49',['Validating the Value Pointed to by a Pointer Argument',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md138',1,'']]],
  ['pointer_20matchers_50',['Pointer Matchers',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2reference_2matchers.html#autotoc_md258',1,'']]],
  ['pointerprintable_51',['PointerPrintable',['../structfoo_1_1_pointer_printable.html',1,'foo']]],
  ['pointerprinter_52',['PointerPrinter',['../structtesting_1_1internal_1_1_pointer_printer.html',1,'testing::internal']]],
  ['points_53',['points',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2googletest_2include_2gtest_2internal_2custom_2_r_e_a_d_m_e.html',1,'Customization Points'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2googlemock_2include_2gmock_2internal_2custom_2_r_e_a_d_m_e.html',1,'Customization Points'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md77',1,'Turning Assertion Failures into Break-Points']]],
  ['polymorphic_20actions_54',['Writing New Polymorphic Actions',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#NewPolyActions',1,'']]],
  ['polymorphic_20matchers_55',['Writing New Polymorphic Matchers',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md170',1,'']]],
  ['polymorphicaction_56',['PolymorphicAction',['../classtesting_1_1_polymorphic_action.html',1,'testing']]],
  ['port_20h_20tt_57',['port h tt',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2googlemock_2include_2gmock_2internal_2custom_2_r_e_a_d_m_e.html#autotoc_md379',1,'Header &lt;tt&gt;gmock-port.h&lt;/tt&gt;'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2googletest_2include_2gtest_2internal_2custom_2_r_e_a_d_m_e.html#autotoc_md388',1,'Header &lt;tt&gt;gtest-port.h&lt;/tt&gt;']]],
  ['precalculatedprimetable_58',['PreCalculatedPrimeTable',['../class_pre_calculated_prime_table.html',1,'']]],
  ['predformatfunctor1_59',['PredFormatFunctor1',['../struct_pred_format_functor1.html',1,'']]],
  ['predformatfunctor2_60',['PredFormatFunctor2',['../struct_pred_format_functor2.html',1,'']]],
  ['predformatfunctor3_61',['PredFormatFunctor3',['../struct_pred_format_functor3.html',1,'']]],
  ['predformatfunctor4_62',['PredFormatFunctor4',['../struct_pred_format_functor4.html',1,'']]],
  ['predformatfunctor5_63',['PredFormatFunctor5',['../struct_pred_format_functor5.html',1,'']]],
  ['predfunctor1_64',['PredFunctor1',['../struct_pred_functor1.html',1,'']]],
  ['predfunctor2_65',['PredFunctor2',['../struct_pred_functor2.html',1,'']]],
  ['predfunctor3_66',['PredFunctor3',['../struct_pred_functor3.html',1,'']]],
  ['predfunctor4_67',['PredFunctor4',['../struct_pred_functor4.html',1,'']]],
  ['predfunctor5_68',['PredFunctor5',['../struct_pred_functor5.html',1,'']]],
  ['predicate_20assertions_69',['Predicate Assertions',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2reference_2assertions.html#predicates',1,'']]],
  ['predicate_20assertions_20for_20better_20error_20messages_70',['Predicate Assertions for Better Error Messages',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md15',1,'']]],
  ['predicate_20format_20functions_71',['Floating-Point Predicate-Format Functions',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md20',1,'']]],
  ['predicate_20formatter_72',['Using a Predicate-Formatter',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md18',1,'']]],
  ['predicate1test_73',['Predicate1Test',['../class_predicate1_test.html',1,'']]],
  ['predicate2test_74',['Predicate2Test',['../class_predicate2_test.html',1,'']]],
  ['predicate3test_75',['Predicate3Test',['../class_predicate3_test.html',1,'']]],
  ['predicate4test_76',['Predicate4Test',['../class_predicate4_test.html',1,'']]],
  ['predicate5test_77',['Predicate5Test',['../class_predicate5_test.html',1,'']]],
  ['predicates_78',['predicates',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2reference_2matchers.html#MatchersAsPredicatesCheat',1,'Using Matchers as Predicates'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md133',1,'Using Matchers as Predicates']]],
  ['predicates_20as_20matchers_79',['Using Predicates as Matchers',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md135',1,'']]],
  ['prefer_20test_20fixtures_20over_20global_20variables_80',['Why should I prefer test fixtures over global variables?',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md98',1,'']]],
  ['premature_20exit_81',['Detecting Test Premature Exit',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md76',1,'']]],
  ['prerequisites_82',['prerequisites',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2quickstart-bazel.html#autotoc_md234',1,'Prerequisites'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2quickstart-cmake.html#autotoc_md239',1,'Prerequisites']]],
  ['pretty_20tedious_83',['I have several test suites which share the same test fixture logic, do I have to define a new test fixture class for each of them? This seems pretty tedious.',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md96',1,'']]],
  ['previous_20threads_20that_20were_20already_20joined_84',['Why does ASSERT_DEATH complain about previous threads that were already joined?',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md101',1,'']]],
  ['primer_85',['Googletest Primer',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2primer.html',1,'']]],
  ['primetable_86',['PrimeTable',['../class_prime_table.html',1,'']]],
  ['print_87',['print',['../class_daily_forecast.html#a8cdc16a8eeeadb2e39b9010fe5d6df20',1,'DailyForecast']]],
  ['print_20your_20values_88',['print your values',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md178',1,'Teaching gMock How to Print Your Values'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md27',1,'Teaching googletest How to Print Your Values']]],
  ['printableviaprintto_89',['PrintableViaPrintTo',['../structfoo_1_1_printable_via_print_to.html',1,'foo']]],
  ['printableviaprinttotemplate_90',['PrintableViaPrintToTemplate',['../classfoo_1_1_printable_via_print_to_template.html',1,'foo']]],
  ['printallindentifiers_91',['PrintAllIndentifiers',['../namespacecpp_1_1ast.html#ab1c1e79e979189e7f3aa93151c189279',1,'cpp::ast']]],
  ['printers_20h_20tt_92',['Header &lt;tt&gt;gtest-printers.h&lt;/tt&gt;',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2googletest_2include_2gtest_2internal_2custom_2_r_e_a_d_m_e.html#autotoc_md394',1,'']]],
  ['printindentifiers_93',['PrintIndentifiers',['../namespacecpp_1_1ast.html#af529298ecedc51e778b85444b7912154',1,'cpp::ast']]],
  ['prints_94',['Controlling How Much Information gMock Prints',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md164',1,'']]],
  ['prints_20a_20warning_20when_20a_20function_20without_20expect_5fcall_20is_20called_20even_20if_20i_20have_20set_20its_20behavior_20using_20on_5fcall_20would_20it_20be_20reasonable_20not_20to_20show_20the_20warning_20in_20this_20case_95',['gMock prints a warning when a function without EXPECT_CALL is called, even if I have set its behavior using ON_CALL. Would it be reasonable not to show the warning in this case?',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md190',1,'']]],
  ['prints_20the_20log_20messages_20in_20a_20death_20test_20s_20child_20process_20only_20when_20the_20test_20fails_20how_20can_20i_20see_20the_20log_20messages_20when_20the_20death_20test_20succeeds_96',['googletest prints the LOG messages in a death test&apos;s child process only when the test fails. How can I see the LOG messages when the death test succeeds?',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md104',1,'']]],
  ['printtostring_97',['PrintToString',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2reference_2testing.html#PrintToString',1,'']]],
  ['printtostringparamname_98',['printtostringparamname',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2reference_2testing.html#PrintToStringParamName',1,'PrintToStringParamName'],['../structtesting_1_1_print_to_string_param_name.html',1,'testing::PrintToStringParamName']]],
  ['private_20code_99',['Testing Private Code',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md51',1,'']]],
  ['private_20or_20protected_20methods_100',['Mocking Private or Protected Methods',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md120',1,'']]],
  ['privatecode_101',['PrivateCode',['../class_private_code.html',1,'']]],
  ['problem_102',['When I call a method on my mock object, the method for the real object is invoked instead. What&apos;s the problem?',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md181',1,'']]],
  ['process_20only_20when_20the_20test_20fails_20how_20can_20i_20see_20the_20log_20messages_20when_20the_20death_20test_20succeeds_103',['googletest prints the LOG messages in a death test&apos;s child process only when the test fails. How can I see the LOG messages when the death test succeeds?',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md104',1,'']]],
  ['program_20crashed_20and_20tt_20scopedmocklog_20tt_20spit_20out_20tons_20of_20messages_20is_20it_20a_20gmock_20bug_104',['My program crashed and &lt;tt&gt;ScopedMockLog&lt;/tt&gt; spit out tons of messages. Is it a gMock bug?',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md185',1,'']]],
  ['programmatically_105',['Registering tests programmatically',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md53',1,'']]],
  ['programs_3a_20advanced_20options_106',['Running Test Programs: Advanced Options',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md59',1,'']]],
  ['project_107',['project',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2googletest_2_r_e_a_d_m_e.html#autotoc_md399',1,'Incorporating Into An Existing CMake Project'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2quickstart-cmake.html#autotoc_md240',1,'Set up a project'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2googletest_2_r_e_a_d_m_e.html#autotoc_md398',1,'Standalone CMake Project']]],
  ['projects_108',['Related Open Source Projects',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2_r_e_a_d_m_e.html#autotoc_md422',1,'']]],
  ['propagating_20fatal_20failures_109',['Propagating Fatal Failures',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md38',1,'']]],
  ['property_20of_20an_20object_110',['Testing a Certain Property of an Object',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md139',1,'']]],
  ['propertyone_111',['PropertyOne',['../class_property_one.html',1,'']]],
  ['propertyrecordingtest_112',['PropertyRecordingTest',['../class_property_recording_test.html',1,'']]],
  ['propertytwo_113',['PropertyTwo',['../class_property_two.html',1,'']]],
  ['protected_20methods_114',['protected methods',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md120',1,'Mocking Private or Protected Methods'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2reference_2testing.html#Environment-protected',1,'Protected Methods'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2reference_2testing.html#Test-protected',1,'Protected Methods']]],
  ['protectedfixturemethodstest_115',['ProtectedFixtureMethodsTest',['../class_protected_fixture_methods_test.html',1,'']]],
  ['proto_20descriptors_20when_20using_20tt_20protocolmessageequals_20tt_20help_116',['I got some run-time errors about invalid proto descriptors when using &lt;tt&gt;ProtocolMessageEquals&lt;/tt&gt;. Help!',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md85',1,'']]],
  ['protobufprinter_117',['ProtobufPrinter',['../structtesting_1_1internal_1_1_protobuf_printer.html',1,'testing::internal']]],
  ['protocolmessageequals_20tt_20help_118',['I got some run-time errors about invalid proto descriptors when using &lt;tt&gt;ProtocolMessageEquals&lt;/tt&gt;. Help!',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md85',1,'']]],
  ['proxytypelist_119',['ProxyTypeList',['../structtesting_1_1internal_1_1_proxy_type_list.html',1,'testing::internal']]],
  ['ptr_20tt_20and_20tt_20assert_5feq_20null_20ptr_20tt_20but_20not_20tt_20expect_5fne_20null_20ptr_20tt_20and_20tt_20assert_5fne_20null_20ptr_20tt_120',['Why does googletest support &lt;tt&gt;EXPECT_EQ(NULL, ptr)&lt;/tt&gt; and &lt;tt&gt;ASSERT_EQ(NULL, ptr)&lt;/tt&gt; but not &lt;tt&gt;EXPECT_NE(NULL, ptr)&lt;/tt&gt; and &lt;tt&gt;ASSERT_NE(NULL, ptr)&lt;/tt&gt;?',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2faq.html#autotoc_md83',1,'']]],
  ['public_20methods_121',['public methods',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2reference_2testing.html#TestSuite-public',1,'Public Methods'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2reference_2testing.html#UnitTest-public',1,'Public Methods'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2reference_2testing.html#TestEventListener-public',1,'Public Methods'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2reference_2testing.html#TestPartResult-public',1,'Public Methods'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2reference_2testing.html#TestProperty-public',1,'Public Methods'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2reference_2testing.html#TestResult-public',1,'Public Methods'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2reference_2testing.html#TestEventListeners-public',1,'Public Methods'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2reference_2testing.html#Test-public',1,'Public Methods'],['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2reference_2testing.html#TestInfo-public',1,'Public Methods']]],
  ['put_20it_122',['Where to Put It',['../md_out_2build_2x64-_debug_2__deps_2googletest-src_2docs_2gmock__for__dummies.html#autotoc_md206',1,'']]]
];
